package com.drownedinsound.data.generatered;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import android.support.annotation.StringDef;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.util.ArrayList;
import java.util.List;

import com.drownedinsound.data.model.BoardListTypes;
// KEEP INCLUDES END
/**
 * Entity mapped to table "BOARD_POST_LIST".
 */
public class BoardPostList {

    /** Not-null value. */
    private String boardListTypeID;
    /** Not-null value. */
    private String displayName;
    /** Not-null value. */
    private String url;
    private long lastFetchedMs;
    private int sectionId;
    private int pageIndex;

    // KEEP FIELDS - put your custom fields here
    @Retention(RetentionPolicy.SOURCE)
    @StringDef({BoardListTypes.MUSIC, BoardListTypes.SOCIAL,BoardListTypes.ANNOUNCEMENTS_CLASSIFIEDS,
            BoardListTypes.FESTIVALS,
            BoardListTypes.ERRORS_SUGGESTIONS,BoardListTypes.MUSICIANS,BoardListTypes.YOUR_MUSIC})
    public @interface BoardPostListType {

    }

    private List<BoardPost> boardPostSummaries = new ArrayList<>();
    // KEEP FIELDS END

    public BoardPostList() {
    }

    public BoardPostList(String boardListTypeID) {
        this.boardListTypeID = boardListTypeID;
    }

    public BoardPostList(String boardListTypeID, String displayName, String url, long lastFetchedMs, int sectionId, int pageIndex) {
        this.boardListTypeID = boardListTypeID;
        this.displayName = displayName;
        this.url = url;
        this.lastFetchedMs = lastFetchedMs;
        this.sectionId = sectionId;
        this.pageIndex = pageIndex;
    }

    /** Not-null value. */
    public String getBoardListTypeID() {
        return boardListTypeID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBoardListTypeID(String boardListTypeID) {
        this.boardListTypeID = boardListTypeID;
    }

    /** Not-null value. */
    public String getDisplayName() {
        return displayName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

    public long getLastFetchedMs() {
        return lastFetchedMs;
    }

    public void setLastFetchedMs(long lastFetchedMs) {
        this.lastFetchedMs = lastFetchedMs;
    }

    public int getSectionId() {
        return sectionId;
    }

    public void setSectionId(int sectionId) {
        this.sectionId = sectionId;
    }

    public int getPageIndex() {
        return pageIndex;
    }

    public void setPageIndex(int pageIndex) {
        this.pageIndex = pageIndex;
    }

    // KEEP METHODS - put your custom methods here

    public List<BoardPost> getBoardPostSummaries() {
        return boardPostSummaries;
    }

    public void setBoardPostSummaries(
            List<BoardPost> boardPostSummaries) {
        this.boardPostSummaries = boardPostSummaries;
    }
    // KEEP METHODS END

}
