package com.drownedinsound.data.generatered;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.drownedinsound.data.generatered.BoardPostList;
import com.drownedinsound.data.generatered.BoardPost;
import com.drownedinsound.data.generatered.BoardPostComment;

import com.drownedinsound.data.generatered.BoardPostListDao;
import com.drownedinsound.data.generatered.BoardPostDao;
import com.drownedinsound.data.generatered.BoardPostCommentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig boardPostListDaoConfig;
    private final DaoConfig boardPostDaoConfig;
    private final DaoConfig boardPostCommentDaoConfig;

    private final BoardPostListDao boardPostListDao;
    private final BoardPostDao boardPostDao;
    private final BoardPostCommentDao boardPostCommentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        boardPostListDaoConfig = daoConfigMap.get(BoardPostListDao.class).clone();
        boardPostListDaoConfig.initIdentityScope(type);

        boardPostDaoConfig = daoConfigMap.get(BoardPostDao.class).clone();
        boardPostDaoConfig.initIdentityScope(type);

        boardPostCommentDaoConfig = daoConfigMap.get(BoardPostCommentDao.class).clone();
        boardPostCommentDaoConfig.initIdentityScope(type);

        boardPostListDao = new BoardPostListDao(boardPostListDaoConfig, this);
        boardPostDao = new BoardPostDao(boardPostDaoConfig, this);
        boardPostCommentDao = new BoardPostCommentDao(boardPostCommentDaoConfig, this);

        registerDao(BoardPostList.class, boardPostListDao);
        registerDao(BoardPost.class, boardPostDao);
        registerDao(BoardPostComment.class, boardPostCommentDao);
    }
    
    public void clear() {
        boardPostListDaoConfig.getIdentityScope().clear();
        boardPostDaoConfig.getIdentityScope().clear();
        boardPostCommentDaoConfig.getIdentityScope().clear();
    }

    public BoardPostListDao getBoardPostListDao() {
        return boardPostListDao;
    }

    public BoardPostDao getBoardPostDao() {
        return boardPostDao;
    }

    public BoardPostCommentDao getBoardPostCommentDao() {
        return boardPostCommentDao;
    }

}
